// Generated by CoffeeScript 1.10.0
var a;

this.wow = 'wow';

a = require('at-lodash');

console.log('w');

describe('', function() {
  return it('', function() {});
});

//# sourceMappingURL=functional_test$.js.map
