// Generated by CoffeeScript 1.10.0
var U, _, u, u_FDD;

_ = require('lodash');

u = require('underscore');

U = require('underscore-contrib');

u_FDD = _.intersection(_.keys(_), _.keys(U));

_.each(u_FDD, function(v) {
  return U["u_" + v] = U[v];
});

_.assign(this, U);

_.assign(this, u);

_.assign(this, _);

//# sourceMappingURL=at_module.js.map
